/*
** Nany - https://nany.io
** This Source Code Form is subject to the terms of the Mozilla Public
** License, v. 2.0. If a copy of the MPL was not distributed with this
** file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/
#pragma once

/* NOTE: this file is generated by cmake */

/*! Nany default website */
#define LIBNANYC_WEBSITE  "@nany_website_url@"

/*! C++ compiler */
#define LIBNANYC_BOOTSTRAP_CXX_COMPILER   "@CMAKE_CXX_COMPILER@"


/*! Nany version version major */
#define LIBNANYC_VERSION_MAJOR  @nany_version_major@

/*! Nany version version minor */
#define LIBNANYC_VERSION_MINOR  @nany_version_minor@

/*! Nany version version patch */
#define LIBNANYC_VERSION_PATCH  @nany_version_patch@

/*! Nany version prerelease */
#define LIBNANYC_VERSION_PRERELEASE "@nany_version_prerelease@"

/*! Nany version metadata */
#define LIBNANYC_VERSION_METADATA "@nany_version_metadata@"

/*! Nany version string */
#define LIBNANYC_VERSION_STR "@nany_version_string@"

/* vim: set ft=cpp: */
